package grails.plugin.extproc.remote;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-05-08T15:33:19.136+02:00
 * Generated source version: 2.6.16
 * 
 */
@WebServiceClient(name = "ExternalProcessServiceService", 
                  wsdlLocation = "/home/henrik/dev/grails-ext-proc-plugin/src/groovy/grails/plugin/extproc/ExternalProcess.wsdl",
                  targetNamespace = "http://extproc.plugin.grails/") 
public class ExternalProcessServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://extproc.plugin.grails/", "ExternalProcessServiceService");
    public final static QName ExternalProcessServicePort = new QName("http://extproc.plugin.grails/", "ExternalProcessServicePort");
    static {
        URL url = ExternalProcessServiceService.class.getResource("/home/henrik/dev/grails-ext-proc-plugin/src/groovy/grails/plugin/extproc/ExternalProcess.wsdl");
        if (url == null) {
            url = ExternalProcessServiceService.class.getClassLoader().getResource("/home/henrik/dev/grails-ext-proc-plugin/src/groovy/grails/plugin/extproc/ExternalProcess.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(ExternalProcessServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/home/henrik/dev/grails-ext-proc-plugin/src/groovy/grails/plugin/extproc/ExternalProcess.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public ExternalProcessServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExternalProcessServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExternalProcessServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExternalProcessServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExternalProcessServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ExternalProcessServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ExternalProcessInterface
     */
    @WebEndpoint(name = "ExternalProcessServicePort")
    public ExternalProcessInterface getExternalProcessServicePort() {
        return super.getPort(ExternalProcessServicePort, ExternalProcessInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExternalProcessInterface
     */
    @WebEndpoint(name = "ExternalProcessServicePort")
    public ExternalProcessInterface getExternalProcessServicePort(WebServiceFeature... features) {
        return super.getPort(ExternalProcessServicePort, ExternalProcessInterface.class, features);
    }

}
