package grails.plugin.extproc.remote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-05-08T15:33:19.129+02:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://extproc.plugin.grails/", name = "ExternalProcessInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface ExternalProcessInterface {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "executeProcess", targetNamespace = "http://extproc.plugin.grails/", className = "grails.plugin.extproc.remote.ExecuteProcess")
    @WebMethod
    @ResponseWrapper(localName = "executeProcessResponse", targetNamespace = "http://extproc.plugin.grails/", className = "grails.plugin.extproc.remote.ExecuteProcessResponse")
    public grails.plugin.extproc.remote.ExternalProcessResult executeProcess(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(name = "input", targetNamespace = "")
        grails.plugin.extproc.remote.ExternalProcessInput input
    );
}
