
package grails.plugin.extproc.remote;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2015-05-08T15:33:19.086+02:00
 * Generated source version: 2.6.16
 * 
 */
public final class ExternalProcessInterface_ExternalProcessServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://extproc.plugin.grails/", "ExternalProcessServiceService");

    private ExternalProcessInterface_ExternalProcessServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ExternalProcessServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExternalProcessServiceService ss = new ExternalProcessServiceService(wsdlURL, SERVICE_NAME);
        ExternalProcessInterface port = ss.getExternalProcessServicePort();  
        
        {
        System.out.println("Invoking executeProcess...");
        java.lang.String _executeProcess_name = "";
        grails.plugin.extproc.remote.ExternalProcessInput _executeProcess_input = null;
        grails.plugin.extproc.remote.ExternalProcessResult _executeProcess__return = port.executeProcess(_executeProcess_name, _executeProcess_input);
        System.out.println("executeProcess.result=" + _executeProcess__return);


        }

        System.exit(0);
    }

}
